services:
  - type: web
    name: nexus-ws
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    autoDeployTrigger: 'commit'
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: EMIT_API_KEY
        sync: false
    region: oregon
